# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.108.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --gc --minify -d ./cd \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./cd
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./cd          
      - name: Push hugo site output to sagayd.github.io
        run: |
          echo HOSTNAME.var is $HOSTNAME
          echo HOSTNAME.cmd is `hostname`
          echo PWD.var is $PWD
          echo PWD.cmd is `pwd`
          echo GHWorkspace.actionvar is ${{ github.workspace }}
          ls - ${{ github.workspace }}
          gh repo clone sagayd/sagayd.github.io
          cd sagayd.github.io
          ls -l 
          git config --global user.name "sagayd"
          git config --global user.email "sagayaraj.d@opsmx.io"
          # git add .
          # git commit -m "Developper_commits"
          # git push
      - run: echo "🍏 This job's status is ${{ job.status }}."  
